### ISSUE TITLE
Issue-1-see-car

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create a HTML outline and drop the image of the users car
- [x] Style the car and interface of the game with CSS
- [x] Make sure user can see their car
- [x] Clean up the CSS styling that is unnecessary 
- [x] Test the functions in a private browser
- [x] Fix any errors left
