### ISSUE TITLE
Issue-2-turn-car

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create classes in CSS that can change the direction of the car
- [x] Create a data model that includes which way the car is facing
- [x] Listen for 'keydown' event on the document
- [x] Remove all unnecessary CSS styling that has no affect
- [x] Test the functionality again in a private browsing session
- [x] Fix all errors
