### ISSUE TITLE
Issue-3-start-car

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Change car to be absolutely positioned
- [x] Add a location to your data model to hold the cars x and y coordinates on the page (x = 0, y = 0)
- [x] Call the function with setinterval to move your car a few pixels every 16 milliseconds for a smooth movement
- [x] Ensure to update y location as car moves to the right
- [x] Add inside event listener keydown function: if a user presses the space key, call the startCar function
- [x] Remove all unnecessary CSS styling that has no effect
- [x] Test the functionality again in a private browsing session
- [x] Fix All errors
