### ISSUE TITLE
Issue-4-stop-car

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a boolean to your data model to indicate whether or not the car is started (default = false)
- [x] Add a line in the start car function that changes the value to true when the function is called
- [x] Inside the if statement in the keydown eventlistener, check if the car is listening for spaces.start is true, and if it is then call the clearinterval function to stop the car
- [x] Remove all unnecessary CSS styling that has no affect
- [x] Test the functionality again in a private browsing session
- [x] Fix all erros
