### ISSUE TITLE
Issue-5-steer-car

### ISSUE THREAD

**Issue by Sportillo10** [Sportillo10/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x] Check for the direction of the car in the start car function and update the location in the right direction accordingly
- [x] Remove all unnecessary CSS styling that has no effect
- [x] Test the functionality again in a private browsing session
- [x] Fix all errors
